#
# NetSurf build configuration example
#
#
# To configure NetSurf's build options create a Makefile.config file. This is
# an example Makefile.config.
#
# To see the available config options, look at Makefile.defaults


# For example, by default, NetSurf builds with BMP support.  If you
# wish to disable this, then uncomment the following line.

override NETSURF_USE_BMP := NO
override NETSURF_USE_GIF := NO
override NETSURF_USE_MNG := NO
override NETSURF_FB_FONTLIB := internal

override NETSURF_USE_LIBICONV_PLUG := NO

override NETSURF_USE_HARU_PDF := NO
override NETSURF_USE_RSVG := NO
override NETSURF_USE_ROSPRITE := NO
override NETSURF_FB_FRONTEND := sdl

override NETSURF_FB_FONTLIB := freetype

override NETSURF_FB_FONTPATH := /usr/share/fonts/truetype/liberation
override NETSURF_FB_FONT_SANS_SERIF := LiberationSans-Regular.ttf
override NETSURF_FB_FONT_SANS_SERIF_BOLD := LiberationSans-Bold.ttf
override NETSURF_FB_FONT_SANS_SERIF_ITALIC := LiberationSans-Italic.ttf
override NETSURF_FB_FONT_SANS_SERIF_ITALIC_BOLD := LiberationSans-BoldItalic.ttf
override NETSURF_FB_FONT_SERIF := LiberationSerif-Regular.ttf
override NETSURF_FB_FONT_SERIF_BOLD := LiberationSerif-Bold.ttf
override NETSURF_FB_FONT_MONOSPACE := LiberationMono-Regular.ttf
override NETSURF_FB_FONT_MONOSPACE_BOLD := LiberationMono-Bold.ttf
override NETSURF_FB_FONT_CURSIVE := LiberationSans-Italic.ttf
override NETSURF_FB_FONT_FANTASY := LiberationSans-Regular.ttf
