#!/bin/sh
#
# Do some basic setup
#

case "$1" in
  start)
	mkdir -p /var/run
	mkdir -p /var/log
	mkdir -p /var/lock
	mkdir -p /var/state
	mkdir -p /var/tmp
	for CONF in /etc/sysctl.conf /etc/sysctl.d/*.conf; do
		[ -f "$CONF" ] && sysctl -p "$CONF" -e >&-
	done
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
