#!/bin/sh
#
# Load Zipit Z2 Alsa settings
#

case "$1" in
  start)
	/usr/sbin/alsactl restore -f /etc/alsa/asound.state
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
