#!/bin/sh
#
# Setup and enable zram
#

case "$1" in
  start)
	echo "16000000" > /sys/block/zram0/disksize
	/sbin/mkswap /dev/zram0
	/sbin/swapon /dev/zram0
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
