#!/bin/sh
#
# Start Zipit Z2 Backlight daemon
#

case "$1" in
  start)
	/usr/sbin/bldaemon &
	;;
  stop)
	killall bldaemon
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
