#!/bin/sh
# Set Zipit Z2 CPU Speed
# Use: cpu <level>
# level can be: max, high, med, low, min
# for max to work you must add the kernel boot paramenter:
# cpufreq-pxa2xx.pxa27x_maxfreq=520
#
# Copyright (c) 2012 Joseph Honold <mozzwald@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# make sure we are root
if [ "$(id -u)" != "0" ]; then
echo "This script must be run as root" 1>&2
    exit 1
fi

if [ $1 == "max" ]; then
echo 520000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_setspeed
    echo "CPU Speed set to 520 MHz"
fi

if [ $1 == "high" ]; then
echo 416000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_setspeed
    echo "CPU Speed set to 416 MHz"
fi

if [ $1 == "med" ]; then
echo 312000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_setspeed
    echo "CPU Speed set to 312 MHz"
fi

if [ $1 == "low" ]; then
echo 208000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_setspeed
    echo "CPU Speed set to 208 MHz"
fi

if [ $1 == "min" ]; then
echo 104000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_setspeed
    echo "CPU Speed set to 104 MHz"
fi
